# permissions to do edit pinneddeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pinneddeployment-editor-role
rules:
- apiGroups:
  - rollout.zeitgeistlabs.io
  resources:
  - pinneddeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rollout.zeitgeistlabs.io
  resources:
  - pinneddeployments/status
  verbs:
  - get
  - patch
  - update
