# permissions to do viewer pinneddeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pinneddeployment-viewer-role
rules:
- apiGroups:
  - rollout.zeitgeistlabs.io
  resources:
  - pinneddeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rollout.zeitgeistlabs.io
  resources:
  - pinneddeployments/status
  verbs:
  - get
